targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/core/model.dart
        options:
          explicit_to_json: true
          generic_argument_factories: true
          field_rename: snake

      freezed:
        enabled: true
        generate_for:
          include:
            - lib/core/model.dart
        options:
          from_json: true
          to_json: true
          copy_with: false
          equal: true